package app.trailblazercombi.haventide.game2.viewModel

import app.trailblazercombi.haventide.game2.data.tilemap.TileData
import app.trailblazercombi.haventide.game2.jetpack.gamescreen.tilemap.Tile
import app.trailblazercombi.haventide.resources.UniversalColorizer
import kotlinx.coroutines.flow.MutableStateFlow

/**
 * A supporting class that maps the click states of individual tiles.
 * The @Composable [Tile] drinks StateFlows generated by this as States.
 *
 * This is the Interface component, unifying [TileStateMap] and [MutableTileStateMap].
 */
interface StateMapForTiles {
    fun getClick(tile: TileData): MutableStateFlow<UniversalColorizer>?
    fun getHighlight(tile: TileData): MutableStateFlow<UniversalColorizer>?

    fun setClick(tile: TileData, newClick: UniversalColorizer)
    fun setHighlight(tile: TileData, newHighlight: UniversalColorizer)

    fun toTileStateMap(): TileStateMap
    fun toMutableTileStateMap(): MutableTileStateMap

    fun unpack(): Map<TileData, Pair<MutableStateFlow<UniversalColorizer>, MutableStateFlow<UniversalColorizer>>>
}
